DROP TABLE orders IF EXISTS;
DROP TABLE customers IF EXISTS;

CREATE TABLE customers (
            id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            first_name VARCHAR(30),
            last_name  VARCHAR_IGNORECASE(30),
            address    VARCHAR(255),
            city       VARCHAR(80),
            telephone  VARCHAR(20)
);

CREATE TABLE orders (
             order_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             customer_id    INTEGER NOT NULL,
             address    VARCHAR(255),
             city       VARCHAR(80),
             telephone  VARCHAR(20)
);

ALTER TABLE orders ADD CONSTRAINT fk_orders_vets FOREIGN KEY (customer_id) REFERENCES customers (id);